alias wip='git commit -am wip && git push'
alias green='git commit -am green'
alias red='git commit -am red'
alias gp='git push'
alias gs='git status'
alias ga='git add * && git status'
alias lsa='ls -A --color=auto'

alias ppa='echo $PATH'
alias gc='git commit -m '
