#!/bin/bash
echo "Setting environment..." &&
    cd $LH_ROOT  &&
    python3 -m venv .env/lh &&
    source .env/lh/bin/activate || exit $?

export _OLD_PYTHONPATH=$PYTHONPATH
export PYTHONPATH=$(pwd):$PYTHONPATH

echo "Creating aliases"
alias obtest='./scripts/test'
alias obsetup='./scripts/setup'
alias obrun='./scripts/run'
alias obbuild='./scripts/build'


